// The bundle-root `index.md` (OKF §8) — the file an agent or a human opens
// first to see what the record holds without reading every concept.
//
// It is derived, but it cannot say so the way every other derived file does:
// OKF permits frontmatter in an index only for `okf_version` (§12), so there is
// nowhere in frontmatter for a `generated` stamp. The marker therefore lives as
// an HTML comment at the top of the body, which OKF does not constrain and
// which a human reading the raw file still sees (T-300).

import type { ParsedConcept } from "./concepts.js";
import { splitFrontmatter } from "./frontmatter.js";

export const INDEX_FILENAME = "index.md";
export const INDEX_MARKER = "<!-- generated by forge index · do not edit -->";

/** Section order: the bundle root first, then type directories alphabetically. */
function sectionOrder(a: string, b: string): number {
  if (a === "") return -1;
  if (b === "") return 1;
  return a.localeCompare(b);
}

/**
 * Renders the index for the concepts a bundle currently holds. Pure: the same
 * concepts always produce the same file, which is what lets doctor detect a
 * stale index by rebuilding and comparing.
 */
export function buildBundleIndex(concepts: readonly ParsedConcept[], okfVersion = "0.2"): string {
  const groups = new Map<string, ParsedConcept[]>();
  for (const concept of concepts) {
    const dir = concept.relPath.includes("/")
      ? concept.relPath.slice(0, concept.relPath.indexOf("/"))
      : "";
    groups.set(dir, [...(groups.get(dir) ?? []), concept]);
  }

  const lines: string[] = [
    "---",
    `okf_version: "${okfVersion}"`,
    "---",
    INDEX_MARKER,
    "",
    "# The record",
    "",
    "The design record for this project, as an Open Knowledge Format bundle. Each",
    "file below is one concept; tools and agents read them directly.",
  ];

  for (const dir of [...groups.keys()].sort(sectionOrder)) {
    const entries = [...(groups.get(dir) ?? [])].sort((a, b) => a.relPath.localeCompare(b.relPath));
    lines.push("", `## ${dir === "" ? "Documents" : dir}`, "");
    for (const concept of entries) {
      const label = concept.title ?? concept.relPath;
      const description = concept.description ?? describe(concept);
      lines.push(`* [${label}](${concept.relPath})${description ? ` - ${description}` : ""}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

/** True when this index was generated rather than hand-written. */
export function isGeneratedIndex(text: string): boolean {
  const body = splitFrontmatter(text).body;
  return body.trimStart().startsWith(INDEX_MARKER);
}

/**
 * A one-line description when the concept declares none, so the index is still
 * useful on a record nobody has written descriptions for. Only says something
 * the title doesn't: an id is worth showing, a type that merely repeats the
 * title is not.
 */
function describe(concept: ParsedConcept): string {
  if (concept.id !== null && concept.type !== null) return `${concept.type} · ${concept.id}`;
  if (concept.type === null || concept.type === concept.title) return "";
  return concept.type;
}
