// Generation markers for derived files (spec/format.md §1 principle 4:
// "Human-written vs derived is explicit"). FeatureLog.md is the first
// derived file; the shape is generic so future derived files reuse it.

const MARKER_RE =
  /^<!--\s*generated by\s+(.+?)\s*·\s*([A-Z][A-Z0-9]*-\d+)\s*·\s*do not edit\s*-->$/;

export interface DerivedMarker {
  generator: string;
  ref: string;
}

export function buildDerivedMarker(generator: string, ref: string): string {
  return `<!-- generated by ${generator} · ${ref} · do not edit -->`;
}

export function parseDerivedMarker(firstLine: string): DerivedMarker | null {
  const match = MARKER_RE.exec(firstLine.trim());
  if (!match?.[1] || !match[2]) return null;
  return { generator: match[1].trim(), ref: match[2] };
}

export function hasDerivedMarker(text: string): boolean {
  return parseDerivedMarker(text.split("\n")[0] ?? "") !== null;
}
