import { describe, expect, it } from "vitest";
import { buildDerivedMarker, hasDerivedMarker, parseDerivedMarker } from "../src/derived.js";

describe("derived markers", () => {
  it("builds the spec §4 marker shape", () => {
    expect(buildDerivedMarker("forge freeze", "FREEZE-004")).toBe(
      "<!-- generated by forge freeze · FREEZE-004 · do not edit -->",
    );
  });

  it("round-trips through parse", () => {
    const marker = buildDerivedMarker("forge freeze", "FREEZE-004");
    expect(parseDerivedMarker(marker)).toEqual({ generator: "forge freeze", ref: "FREEZE-004" });
  });

  it("detects a marker as the file's first line", () => {
    const text = `${buildDerivedMarker("forge freeze", "FREEZE-004")}\n\n# Feature log\n`;
    expect(hasDerivedMarker(text)).toBe(true);
  });

  it("returns null/false for hand-written content", () => {
    expect(parseDerivedMarker("# Feature log")).toBeNull();
    expect(hasDerivedMarker("# Feature log\n")).toBe(false);
  });
});
