import { execFileSync } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parseConcept } from "@forgedesign/format";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { checksSatisfied, readCheckConfigs, runCheck } from "../src/check.js";
import { runFreeze } from "../src/commands/freeze.js";
import { makeDesignRepo } from "./helpers.js";

let sandbox: string;
let previousForgeHome: string | undefined;

beforeEach(async () => {
  sandbox = await fs.mkdtemp(path.join(tmpdir(), "forge-check-"));
  previousForgeHome = process.env.FORGE_HOME;
  process.env.FORGE_HOME = path.join(sandbox, ".forge");
});

afterEach(async () => {
  if (previousForgeHome === undefined) delete process.env.FORGE_HOME;
  else process.env.FORGE_HOME = previousForgeHome;
  await fs.rm(sandbox, { recursive: true, force: true });
});

const REPORT = {
  checker: "lint",
  version: "1.2.0",
  score: 91,
  summary: "One contrast failure.",
  findings: [
    {
      rule: "contrast-aa",
      severity: "error",
      message: "Body text is 3.2:1 — and it cites TASK-999 in passing.",
      route: "/",
      selector: "main p",
      fix: "Use the on-surface token.",
    },
    { rule: "note", severity: "info", message: "Scanned 1 route." },
  ],
};

/** A repo whose forge.json names one checker: a script that prints a fixed report. */
async function repoWithChecker(report: unknown = REPORT): Promise<string> {
  const root = await makeDesignRepo(sandbox);
  await fs.writeFile(
    path.join(root, "checker.mjs"),
    `console.log(JSON.stringify(${JSON.stringify(report)}));\n`,
    "utf8",
  );
  const manifest = JSON.parse(await fs.readFile(path.join(root, "forge.json"), "utf8"));
  manifest.checks = [{ name: "lint", command: "node checker.mjs" }];
  await fs.writeFile(path.join(root, "forge.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  git(root, "add", "-A");
  git(root, "commit", "-qm", "add a checker");
  return root;
}

const git = (root: string, ...args: string[]) =>
  execFileSync("git", args, { cwd: root }).toString().trim();

describe("readCheckConfigs", () => {
  it("reads the entries and refuses a name doctor already uses or a duplicate", () => {
    expect(readCheckConfigs({})).toEqual([]);
    expect(readCheckConfigs({ checks: [{ name: "lint", command: "x", dir: "app" }] })).toEqual([
      { name: "lint", command: "x", dir: "app" },
    ]);
    expect(() => readCheckConfigs({ checks: [{ name: "doctor", command: "x" }] })).toThrow(
      /doctor's own name/,
    );
    expect(() =>
      readCheckConfigs({
        checks: [
          { name: "a", command: "x" },
          { name: "a", command: "y" },
        ],
      }),
    ).toThrow(/listed twice/);
    expect(() => readCheckConfigs({ checks: [{ name: "a/b", command: "x" }] })).toThrow(/filename/);
  });
});

describe("forge check (TASK-456, DDR-127)", () => {
  it("writes one derived Check concept per checker, doctor included, with the JSON beside it", async () => {
    const root = await repoWithChecker();
    const result = await runCheck({ tag: "alpha", cwd: root });

    expect(result.commit).toBe(git(root, "rev-parse", "HEAD"));
    expect(result.dir).toBe(path.join("design", "checks", "alpha"));
    expect(result.reports.map((r) => [r.checker, r.findings, r.errors, r.score])).toEqual([
      ["doctor", 0, 0, null],
      ["lint", 2, 1, 91],
    ]);

    const lint = await fs.readFile(path.join(root, "design/checks/alpha/lint.md"), "utf8");
    const concept = parseConcept("checks/alpha/lint.md", lint);
    expect(concept.problems).toEqual([]);
    expect(concept.frontmatter).toMatchObject({
      type: "Check",
      checker: "lint",
      version: "1.2.0",
      target: "alpha",
      commit: result.commit,
      command: "node checker.mjs",
      score: 91,
      findings: 2,
      errors: 1,
      warnings: 0,
    });
    expect(concept.generated?.by).toBe("forge check");
    expect(lint).toContain("<!-- generated by forge check · alpha · do not edit -->");
    expect(lint).toContain("lint checked alpha at commit");
    expect(lint).toContain("1 error, 1 info. One contrast failure.");
    // Findings are a fenced block: a message may quote an id, and a quoted id
    // is a literal, not a reference doctor must resolve.
    expect(lint).toContain(
      "```text\nerror    contrast-aa  Body text is 3.2:1 — and it cites TASK-999 in passing.  · / main p  → Use the on-surface token.",
    );
    const sidecar = JSON.parse(
      await fs.readFile(path.join(root, "design/checks/alpha/lint.json"), "utf8"),
    );
    expect(sidecar).toEqual({ ...REPORT, checker: "lint" });

    const doctor = await fs.readFile(path.join(root, "design/checks/alpha/doctor.md"), "utf8");
    expect(doctor).toContain("forge doctor: clean");
    expect(doctor).toContain("No findings.");
    // The index lists the new concepts, and the record is still clean.
    expect(await fs.readFile(path.join(root, "design/index.md"), "utf8")).toContain(
      "checks/alpha/lint.md",
    );
    const { runDoctor } = await import("../src/doctor.js");
    expect((await runDoctor(root)).findings).toEqual([]);
  });

  it("refuses a dirty tree, because a report names the commit it checked", async () => {
    const root = await repoWithChecker();
    await fs.writeFile(
      path.join(root, "design/brief.md"),
      "---\ntype: Brief\ntitle: Brief\n---\nchanged\n",
    );
    await expect(runCheck({ tag: "alpha", cwd: root })).rejects.toThrow(/not clean/);
  });

  it("lets a re-run replace its own reports without a commit in between", async () => {
    const root = await repoWithChecker();
    await runCheck({ tag: "alpha", cwd: root });
    await expect(runCheck({ tag: "alpha", cwd: root })).resolves.toMatchObject({ tag: "alpha" });
  });

  it("names the checker that did not produce a report, and quotes what it printed", async () => {
    const root = await repoWithChecker();
    await fs.writeFile(path.join(root, "checker.mjs"), 'console.log("Scanning... done");\n');
    git(root, "commit", "-qam", "break the checker");
    await expect(runCheck({ tag: "alpha", cwd: root })).rejects.toThrow(
      /checker "lint" did not print a JSON report — it ended with: Scanning... done/,
    );

    await fs.writeFile(
      path.join(root, "checker.mjs"),
      'console.log(JSON.stringify({ checker: "lint", findings: [{ rule: "r", severity: "fatal", message: "m" }] }));\n',
    );
    git(root, "commit", "-qam", "bad severity");
    await expect(runCheck({ tag: "alpha", cwd: root })).rejects.toThrow(
      /checker "lint": finding 1/,
    );

    await fs.writeFile(path.join(root, "checker.mjs"), "process.exit(3);\n");
    git(root, "commit", "-qam", "crash");
    await expect(runCheck({ tag: "alpha", cwd: root })).rejects.toThrow(
      /checker "lint" failed to run/,
    );
  });
});

describe("forge freeze --require-check", () => {
  it("refuses without reports, accepts the commit that carries them, and refuses once the tree moves on", async () => {
    const root = await repoWithChecker();
    const recordRoot = "design";

    await expect(
      runFreeze({ tag: "alpha", message: "first", cwd: root, requireCheck: true }),
    ).rejects.toThrow(/doctor has no report; lint has no report — run `forge check alpha`/);
    expect(git(root, "tag")).toBe("");

    await runCheck({ tag: "alpha", cwd: root });
    git(root, "add", "-A");
    git(root, "commit", "-qm", "check reports for alpha");
    // The reports name the commit before this one; nothing but reports changed since.
    expect(
      await checksSatisfied(root, recordRoot, "alpha", git(root, "rev-parse", "HEAD")),
    ).toEqual({
      missing: [],
      stale: [],
    });
    const result = await runFreeze({
      tag: "alpha",
      message: "first",
      cwd: root,
      requireCheck: true,
    });
    expect(result.record.tag).toBe("alpha");

    // A later change makes the same reports stale for the next tag.
    await fs.writeFile(
      path.join(root, "design/brief.md"),
      "---\ntype: Brief\ntitle: Brief\n---\nmoved on\n",
    );
    git(root, "commit", "-qam", "brief changed");
    await runCheck({ tag: "beta", cwd: root });
    git(root, "add", "-A");
    git(root, "commit", "-qm", "check reports for beta");
    await fs.writeFile(
      path.join(root, "design/brief.md"),
      "---\ntype: Brief\ntitle: Brief\n---\nmoved again\n",
    );
    git(root, "commit", "-qam", "brief changed again");
    await expect(
      runFreeze({ tag: "beta", message: "second", cwd: root, requireCheck: true }),
    ).rejects.toThrow(
      /doctor's report is for an older commit; lint's report is for an older commit/,
    );
  });

  it("does not gate a freeze that did not ask for it", async () => {
    const root = await repoWithChecker();
    await expect(runFreeze({ tag: "alpha", message: "first", cwd: root })).resolves.toMatchObject({
      record: { tag: "alpha" },
    });
  });
});
