import { execFileSync } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parseConcept } from "@forgedesign/format";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { initProject } from "../src/commands/init.js";
import { generateFeatureLog } from "../src/feature-log.js";
import type { FreezeRecord } from "../src/freezes.js";

let sandbox: string;
let root: string;
let previousForgeHome: string | undefined;

beforeEach(async () => {
  sandbox = await fs.mkdtemp(path.join(tmpdir(), "forge-featurelog-"));
  previousForgeHome = process.env.FORGE_HOME;
  process.env.FORGE_HOME = path.join(sandbox, ".forge");
  root = path.join(sandbox, "demo");
  await initProject(root);
  git("add", "-A");
  git("commit", "-qm", "init");
});

afterEach(async () => {
  if (previousForgeHome === undefined) delete process.env.FORGE_HOME;
  else process.env.FORGE_HOME = previousForgeHome;
  await fs.rm(sandbox, { recursive: true, force: true });
});

function git(...args: string[]): void {
  execFileSync("git", args, {
    cwd: root,
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: "t",
      GIT_AUTHOR_EMAIL: "t@t",
      GIT_COMMITTER_NAME: "t",
      GIT_COMMITTER_EMAIL: "t@t",
    },
  });
}

/** Replace the ledger's Done section, then commit and tag it as a freeze. */
async function freezeWith(tag: string, done: string[]): Promise<void> {
  const ledgerPath = path.join(root, "design", "todos.md");
  const current = await fs.readFile(ledgerPath, "utf8");
  const concept = parseConcept("todos.md", current);
  const body = [
    "## Todo",
    "",
    "## Doing",
    "",
    "## Done",
    ...done.map((line) => `- [x] ${line}\n  status: done · opened: 2026-07-01`),
    "",
    "## Deferred",
    "",
  ].join("\n");
  await fs.writeFile(
    ledgerPath,
    `${current.slice(0, current.length - concept.body.length)}${body}`,
    "utf8",
  );
  git("add", "-A");
  // A freeze that closed nothing changes no files, which is exactly the case
  // the "nothing closed" section exists for.
  git("commit", "-q", "--allow-empty", "-m", tag);
  git("tag", "-a", tag, "-m", tag);
}

const freeze = (tag: string, date: string): FreezeRecord => ({
  tag,
  date,
  commit: "x",
  previewUrl: null,
  storybookUrl: null,
  pin: "1",
  snapshotId: null,
});

describe("the feature log (T-238)", () => {
  it("lists what reached Done between consecutive freezes, newest first", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await freezeWith("beta", ["TASK-001 Ship the picker", "TASK-002 Add the recap quiz"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15"),
    ]);

    expect(result.path).toBe(path.join("design", "feature-log.md"));
    expect(result.freezes.map((f) => f.tag)).toEqual(["beta", "alpha"]);
    expect(result.freezes[0]?.closed).toEqual([{ id: "TASK-002", title: "Add the recap quiz" }]);
    // the first freeze carries everything done up to it
    expect(result.freezes[1]?.closed).toEqual([{ id: "TASK-001", title: "Ship the picker" }]);
  });

  it("writes a concept with the derived marker and the latest freeze in frontmatter", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await generateFeatureLog(root, [freeze("alpha", "2026-07-01")]);

    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    const concept = parseConcept("feature-log.md", text);
    expect(concept.problems).toEqual([]);
    expect(concept.frontmatter).toMatchObject({ type: "Feature Log", freeze: "FREEZE-001" });
    expect(concept.generated?.by).toBe("forge-cli/0.1.0");
    expect(concept.body.split("\n")[0]).toBe(
      "<!-- generated by forge freeze · FREEZE-001 · do not edit -->",
    );
    expect(text).toContain("## alpha — 2026-07-01");
    expect(text).toContain("- TASK-001 Ship the picker");
  });

  it("says so plainly when a release closed nothing", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await freezeWith("beta", ["TASK-001 Ship the picker"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15"),
    ]);

    expect(result.freezes[0]?.closed).toEqual([]);
    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    expect(text).toContain("Nothing closed since the previous freeze.");
  });

  it("is reproducible — regenerating from the same tags gives the same sections", async () => {
    await freezeWith("alpha", ["TASK-001 One"]);
    await freezeWith("beta", ["TASK-001 One", "TASK-002 Two"]);
    const freezes = [freeze("alpha", "2026-07-01"), freeze("beta", "2026-07-15")];

    const first = await generateFeatureLog(root, freezes);
    const second = await generateFeatureLog(root, freezes);

    expect(second.freezes).toEqual(first.freezes);
  });

  it("does nothing on a record with no freezes yet", async () => {
    expect(await generateFeatureLog(root, [])).toEqual({ path: null, freezes: [], warnings: [] });
  });

  it("warns rather than inventing content when a tag has no ledger", async () => {
    git("tag", "-a", "orphan", "-m", "orphan");
    await fs.rm(path.join(root, "design", "todos.md"));
    git("add", "-A");
    git("commit", "-qm", "drop ledger");
    git("tag", "-a", "later", "-m", "later");

    const result = await generateFeatureLog(root, [
      freeze("orphan", "2026-07-01"),
      freeze("later", "2026-07-15"),
    ]);

    expect(result.warnings.join(" ")).toContain("no task ledger at later");
  });
});

describe("the feature log keeps the bundle index true (T-238)", () => {
  it("regenerates the index, since it has just added a concept", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await generateFeatureLog(root, [freeze("alpha", "2026-07-01")]);

    const index = await fs.readFile(path.join(root, "design", "index.md"), "utf8");
    expect(index).toContain("feature-log");
  });
});
