import { execFileSync } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parseConcept } from "@forgedesign/format";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { initProject } from "../src/commands/init.js";
import { generateFeatureLog } from "../src/feature-log.js";
import type { FreezeRecord } from "../src/freezes.js";

let sandbox: string;
let root: string;
let previousForgeHome: string | undefined;

beforeEach(async () => {
  sandbox = await fs.mkdtemp(path.join(tmpdir(), "forge-featurelog-"));
  previousForgeHome = process.env.FORGE_HOME;
  process.env.FORGE_HOME = path.join(sandbox, ".forge");
  root = path.join(sandbox, "demo");
  await initProject(root);
  git("add", "-A");
  git("commit", "-qm", "init");
});

afterEach(async () => {
  if (previousForgeHome === undefined) delete process.env.FORGE_HOME;
  else process.env.FORGE_HOME = previousForgeHome;
  await fs.rm(sandbox, { recursive: true, force: true });
});

function git(...args: string[]): void {
  execFileSync("git", args, {
    cwd: root,
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: "t",
      GIT_AUTHOR_EMAIL: "t@t",
      GIT_COMMITTER_NAME: "t",
      GIT_COMMITTER_EMAIL: "t@t",
    },
  });
}

/** Replace the ledger's Done section, then commit and tag it as a freeze. */
async function freezeWith(tag: string, done: string[]): Promise<void> {
  const ledgerPath = path.join(root, "design", "todos.md");
  const current = await fs.readFile(ledgerPath, "utf8");
  const concept = parseConcept("todos.md", current);
  const body = [
    "## Todo",
    "",
    "## Doing",
    "",
    "## Done",
    ...done.map((line) => `- [x] ${line}\n  status: done · opened: 2026-07-01`),
    "",
    "## Deferred",
    "",
  ].join("\n");
  await fs.writeFile(
    ledgerPath,
    `${current.slice(0, current.length - concept.body.length)}${body}`,
    "utf8",
  );
  git("add", "-A");
  // A freeze that closed nothing changes no files, which is exactly the case
  // the "nothing closed" section exists for.
  git("commit", "-q", "--allow-empty", "-m", tag);
  git("tag", "-a", tag, "-m", tag);
}

const freeze = (tag: string, date: string, routes?: Record<string, string>): FreezeRecord => ({
  tag,
  date,
  commit: "x",
  previewUrl: null,
  storybookUrl: null,
  pin: "1",
  snapshotId: null,
  ...(routes ? { routes } : {}),
});

describe("the feature log (T-238)", () => {
  it("lists what reached Done between consecutive freezes, newest first", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await freezeWith("beta", ["TASK-001 Ship the picker", "TASK-002 Add the recap quiz"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15"),
    ]);

    expect(result.path).toBe(path.join("design", "feature-log.md"));
    expect(result.freezes.map((f) => f.tag)).toEqual(["beta", "alpha"]);
    expect(result.freezes[0]?.closed).toEqual([{ id: "TASK-002", title: "Add the recap quiz" }]);
    // the first freeze carries everything done up to it
    expect(result.freezes[1]?.closed).toEqual([{ id: "TASK-001", title: "Ship the picker" }]);
  });

  it("writes a concept with the derived marker and the latest freeze in frontmatter", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await generateFeatureLog(root, [freeze("alpha", "2026-07-01")]);

    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    const concept = parseConcept("feature-log.md", text);
    expect(concept.problems).toEqual([]);
    expect(concept.frontmatter).toMatchObject({ type: "Feature Log", freeze: "FREEZE-001" });
    expect(concept.generated?.by).toBe("forge-cli/0.1.0");
    expect(concept.body.split("\n")[0]).toBe(
      "<!-- generated by forge freeze · FREEZE-001 · do not edit -->",
    );
    expect(text).toContain("## alpha — 2026-07-01");
    expect(text).toContain("- TASK-001 Ship the picker");
  });

  it("says so plainly when a release closed nothing", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await freezeWith("beta", ["TASK-001 Ship the picker"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15"),
    ]);

    expect(result.freezes[0]?.closed).toEqual([]);
    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    expect(text).toContain("Nothing closed since the previous freeze.");
  });

  it("is reproducible — regenerating from the same tags gives the same sections", async () => {
    await freezeWith("alpha", ["TASK-001 One"]);
    await freezeWith("beta", ["TASK-001 One", "TASK-002 Two"]);
    const freezes = [freeze("alpha", "2026-07-01"), freeze("beta", "2026-07-15")];

    const first = await generateFeatureLog(root, freezes);
    const second = await generateFeatureLog(root, freezes);

    expect(second.freezes).toEqual(first.freezes);
  });

  it("does nothing on a record with no freezes yet", async () => {
    expect(await generateFeatureLog(root, [])).toEqual({ path: null, freezes: [], warnings: [] });
  });

  it("warns rather than inventing content when a tag has no ledger", async () => {
    git("tag", "-a", "orphan", "-m", "orphan");
    await fs.rm(path.join(root, "design", "todos.md"));
    git("add", "-A");
    git("commit", "-qm", "drop ledger");
    git("tag", "-a", "later", "-m", "later");

    const result = await generateFeatureLog(root, [
      freeze("orphan", "2026-07-01"),
      freeze("later", "2026-07-15"),
    ]);

    expect(result.warnings.join(" ")).toContain("no task ledger at later");
  });
});

describe("which screens changed (TASK-461)", () => {
  it("lists the routes that changed between two hashed freezes, with the feedback each addressed", async () => {
    await freezeWith("alpha", ["TASK-001 One"]);
    await fs.mkdir(path.join(root, "design", "feedback"), { recursive: true });
    await fs.writeFile(
      path.join(root, "design", "feedback", "FEEDBACK-001.md"),
      "---\ntype: Feedback\nid: FEEDBACK-001\ntitle: The rules should show first\ndate: 2026-07-10\nfeedback_status: done\nsource: review\nresolution: TASK-002\nroute: /register/\naddressed_in: beta\n---\n> The rules should show first\n",
      "utf8",
    );
    await fs.writeFile(
      path.join(root, "design", "feedback", "FEEDBACK-002.md"),
      "---\ntype: Feedback\nid: FEEDBACK-002\ntitle: A remark with no screen\ndate: 2026-07-10\nfeedback_status: done\nsource: meeting\nresolution: TASK-002\naddressed_in: beta\n---\n> A remark with no screen\n",
      "utf8",
    );
    await freezeWith("beta", ["TASK-001 One", "TASK-002 Two"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01", { "/": "a1", "/register": "b1", "/old": "c" }),
      freeze("beta", "2026-07-15", { "/": "a1", "/register": "b2", "/welcome": "d" }),
    ]);

    const [beta, alpha] = result.freezes;
    expect(beta?.screens).toEqual({
      kind: "compared",
      previousTag: "alpha",
      screens: [
        { route: "/", status: "unchanged" },
        { route: "/old", status: "removed" },
        { route: "/register", status: "changed" },
        { route: "/welcome", status: "new" },
      ],
    });
    // The reviewer's `/register/` meets the build's `/register`.
    expect(beta?.addressed).toEqual([
      { id: "FEEDBACK-001", title: "The rules should show first", route: "/register" },
      { id: "FEEDBACK-002", title: "A remark with no screen", route: null },
    ]);
    expect(alpha?.screens.kind).toBe("first");

    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    const betaSection = text.slice(text.indexOf("## beta"), text.indexOf("## alpha"));
    expect(betaSection).toContain("### Screens");
    expect(betaSection).toContain("- `/register` changed — addresses FEEDBACK-001");
    expect(betaSection).toContain("- `/welcome` new");
    expect(betaSection).toContain("- `/old` removed");
    expect(betaSection).not.toContain("`/` unchanged");
    expect(betaSection).toContain("- also addresses FEEDBACK-002");
    expect(text.slice(text.indexOf("## alpha"))).toContain("First freeze — every screen is new.");
  });

  it("adds the manifest's declared intent beside the derived status, read at the tag (TASK-468)", async () => {
    await freezeWith("alpha", ["TASK-001 One"]);
    await fs.mkdir(path.join(root, "design", "feedback"), { recursive: true });
    await fs.writeFile(
      path.join(root, "design", "feedback", "FEEDBACK-001.md"),
      "---\ntype: Feedback\nid: FEEDBACK-001\ntitle: Show the rules first\ndate: 2026-07-10\nfeedback_status: done\nsource: review\nresolution: TASK-002\nroute: /register\naddressed_in: beta\n---\n> Show the rules first\n",
      "utf8",
    );
    // `/register/` in the manifest is the build's `/register`, as it is for feedback.
    await fs.writeFile(
      path.join(root, "design", "pages.md"),
      "---\ntype: Page Manifest\ntitle: Pages\n---\n- / · Home — FLOW-001\n- /register/ · Sign up — STORY-002, TASK-002\n",
      "utf8",
    );
    await freezeWith("beta", ["TASK-001 One", "TASK-002 Two"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01", { "/": "a1", "/register": "b1" }),
      freeze("beta", "2026-07-15", { "/": "a1", "/register": "b2", "/welcome": "d" }),
    ]);

    const [beta, alpha] = result.freezes;
    expect(beta?.pages).toEqual({
      "/": { title: "Home", refs: ["FLOW-001"] },
      "/register": { title: "Sign up", refs: ["STORY-002", "TASK-002"] },
    });
    // The manifest did not exist at alpha, so alpha's section carries none of it.
    expect(alpha?.pages).toEqual({});

    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    const betaSection = text.slice(text.indexOf("## beta"), text.indexOf("## alpha"));
    // Derived status, then declared intent, then the feedback — in that order.
    expect(betaSection).toContain(
      "- `/register` changed — Sign up (STORY-002, TASK-002) — addresses FEEDBACK-001",
    );
    // A route with no row reads exactly as it did before.
    expect(betaSection).toContain("- `/welcome` new\n");
    expect(text.slice(text.indexOf("## alpha"))).toContain("- `/register` new\n");
  });

  it("says what it cannot compare, rather than guessing, when a freeze recorded no hashes", async () => {
    await freezeWith("alpha", ["TASK-001 One"]);
    await freezeWith("beta", ["TASK-001 One"]);
    await freezeWith("gamma", ["TASK-001 One"]);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15", { "/": "a" }),
      freeze("gamma", "2026-07-20", { "/": "a" }),
    ]);
    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");

    expect(result.freezes.map((f) => f.screens.kind)).toEqual([
      "compared",
      "baseline-unrecorded",
      "unrecorded",
    ]);
    expect(text).toContain("No screen changed since beta.");
    expect(text).toContain("alpha recorded no route hashes");
    expect(text).toContain("Route hashes were not recorded for this freeze");
  });

  it("lists the decisions that reached accepted between the tags, once", async () => {
    await freezeWith("alpha", []);
    const decisions = path.join(root, "design", "decisions");
    const ddr = (id: string, status: string, extra = "") =>
      `---\ntype: Decision\nid: ${id}\ntitle: ${id} says so\ndate: 2026-07-10\ndecision_status: ${status}\n${extra}---\n## Decision\n\nX.\n`;
    await fs.writeFile(
      path.join(decisions, "DDR-001-first.md"),
      ddr("DDR-001", "accepted"),
      "utf8",
    );
    await fs.writeFile(path.join(decisions, "DDR-002-second.md"), ddr("DDR-002", "draft"), "utf8");
    await freezeWith("beta", []);
    // DDR-001 only gains a back-reference here; DDR-002 is the one accepted now.
    await fs.writeFile(
      path.join(decisions, "DDR-001-first.md"),
      ddr("DDR-001", "accepted", "amended_by: [DDR-002]\n"),
      "utf8",
    );
    await fs.writeFile(
      path.join(decisions, "DDR-002-second.md"),
      ddr("DDR-002", "accepted", "amends: [DDR-001]\n"),
      "utf8",
    );
    await freezeWith("gamma", []);

    const result = await generateFeatureLog(root, [
      freeze("alpha", "2026-07-01"),
      freeze("beta", "2026-07-15"),
      freeze("gamma", "2026-07-20"),
    ]);

    const byTag = Object.fromEntries(
      result.freezes.map((f) => [f.tag, f.accepted.map((d) => d.id)]),
    );
    expect(byTag).toEqual({ alpha: [], beta: ["DDR-001"], gamma: ["DDR-002"] });
    const text = await fs.readFile(path.join(root, "design", "feature-log.md"), "utf8");
    expect(text).toContain("### Decisions accepted\n\n- DDR-002 DDR-002 says so");
  });
});

describe("the feature log keeps the bundle index true (T-238)", () => {
  it("regenerates the index, since it has just added a concept", async () => {
    await freezeWith("alpha", ["TASK-001 Ship the picker"]);
    await generateFeatureLog(root, [freeze("alpha", "2026-07-01")]);

    const index = await fs.readFile(path.join(root, "design", "index.md"), "utf8");
    expect(index).toContain("feature-log");
  });
});
