import { execFileSync } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { inflateRawSync } from "node:zlib";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { runFreeze } from "../src/commands/freeze.js";
import { collectHandoffContent, generateHandoffPack } from "../src/handoff.js";
import { makeDesignRepo } from "./helpers.js";

let sandbox: string;
let previousForgeHome: string | undefined;

const INPUTS = {
  tag: "beta",
  message: "second round",
  date: "2026-07-02",
  previewUrl: "https://demo-preview-abc.vercel.app",
  storybookUrl: "https://demo-storybook-abc.vercel.app",
};

/** A v0.2 decision, hard-wrapped the way the record writes them. */
const decision = (id: string, title: string, status = "accepted") =>
  `---\ntype: Decision\nid: ${id}\ntitle: ${title}\ndate: 2026-07-01\ndecision_status: ${status}\ncontext_source: test\n---\n## Decision\n\nWidgets are the primary unit\nof composition.\n\n## Why\n\nBecause.\n`;

const ACCEPTED_DDR = decision("DDR-001", "Use widgets");
const DRAFT_DDR = decision("DDR-002", "Still thinking", "draft");

beforeEach(async () => {
  sandbox = await fs.mkdtemp(path.join(tmpdir(), "forge-handoff-"));
  previousForgeHome = process.env.FORGE_HOME;
  process.env.FORGE_HOME = path.join(sandbox, ".forge");
});

afterEach(async () => {
  if (previousForgeHome === undefined) delete process.env.FORGE_HOME;
  else process.env.FORGE_HOME = previousForgeHome;
  await fs.rm(sandbox, { recursive: true, force: true });
});

describe("collectHandoffContent", () => {
  it("gathers glossary bullets, user stories, and accepted DDRs only", async () => {
    const root = await makeDesignRepo(sandbox);
    // The pack reads the record's own concepts now (T-256), so the fixture
    // seeds those rather than the v1 artifacts/ stubs init no longer writes.
    await fs.mkdir(path.join(root, "design/glossary"), { recursive: true });
    await fs.writeFile(
      path.join(root, "design/glossary/widget.md"),
      "---\ntype: Term\ntitle: Widget\n---\na thing.\n",
    );
    await fs.writeFile(
      path.join(root, "design/glossary/gadget.md"),
      "---\ntype: Term\ntitle: Gadget\n---\nanother thing.\n",
    );
    await fs.mkdir(path.join(root, "design/stories"), { recursive: true });
    await fs.writeFile(
      path.join(root, "design/stories/STORY-001.md"),
      "---\ntype: Story\nid: STORY-001\ntitle: As a PM, I want pins.\n---\n",
    );
    // The pack reads the bundle's decisions (TASK-464) — it used to read a root
    // `decisions/` in the pre-0.2 prose format, which every current record
    // lacks, so the section was always empty.
    await fs.writeFile(path.join(root, "design/decisions/DDR-001-widgets.md"), ACCEPTED_DDR);
    await fs.writeFile(path.join(root, "design/decisions/DDR-002-draft.md"), DRAFT_DDR);

    const content = await collectHandoffContent(root, INPUTS);
    // Alphabetical, because the bundle scan is path-sorted — a better order for
    // a glossary than whatever order the files happened to be written in.
    expect(content.glossary).toEqual(["Gadget — another thing.", "Widget — a thing."]);
    expect(content.userStories).toEqual(["As a PM, I want pins."]);
    expect(content.ddrs.map((d) => d.title)).toEqual(["DDR-001 — Use widgets"]);
    // The whole paragraph, unwrapped, not its first line.
    expect(content.ddrs[0]?.decision).toBe("Widgets are the primary unit of composition.");
    expect(content.ddrs[0]?.date).toBe("2026-07-01");
    expect(content.previousTag).toBeNull();
    expect(content.openQuestions).toEqual([]);
    expect(content.checks).toEqual([]);
  });

  it("lists the check reports written for the version being handed over (TASK-464, DDR-127)", async () => {
    const root = await makeDesignRepo(sandbox);
    const report = (tag: string, checker: string, front: string) =>
      fs.writeFile(
        path.join(root, `design/checks/${tag}/${checker}.md`),
        `---\ntype: Check\ntitle: ${checker} on ${tag}\nchecker: ${checker}\ntarget: ${tag}\ncommit: abc\ndate: 2026-07-02\n${front}generated: { by: forge check, at: 2026-07-02T00:00:00Z }\n---\n<!-- generated by forge check · ${tag} · do not edit -->\n\nNo findings.\n`,
      );
    await fs.mkdir(path.join(root, "design/checks/beta"), { recursive: true });
    await fs.mkdir(path.join(root, "design/checks/alpha"), { recursive: true });
    await report("beta", "doctor", "findings: 0\nerrors: 0\nwarnings: 0\n");
    await report("beta", "lint", "score: 91\nfindings: 3\nerrors: 1\nwarnings: 1\n");
    await report("alpha", "doctor", "findings: 2\nerrors: 2\nwarnings: 0\n"); // another version's

    const content = await collectHandoffContent(root, INPUTS);
    expect(content.checks).toEqual([
      { checker: "doctor", findings: 0, errors: 0, warnings: 0, score: null },
      { checker: "lint", findings: 3, errors: 1, warnings: 1, score: 91 },
    ]);
    const { files } = await generateHandoffPack(root, INPUTS);
    const xml = zipEntry(await fs.readFile(files[1] as string), "word/document.xml");
    expect(xml).toContain("Checks");
    expect(xml).toContain("doctor — no findings");
    expect(xml).toContain("lint — 1 error, 1 warning, 1 info · score 91");
  });

  it("limits DDRs to those accepted since the previous freeze tag", async () => {
    const root = await makeDesignRepo(sandbox);
    const git = (...args: string[]) => execFileSync("git", args, { cwd: root });
    await fs.writeFile(path.join(root, "design/decisions/DDR-001-widgets.md"), ACCEPTED_DDR);
    git("add", "-A");
    git("commit", "-m", "ddr-1");
    await runFreeze({ tag: "alpha", message: "first", cwd: root });

    // A decision accepted after the alpha freeze — and the earlier one gaining
    // only a back-reference, which is not a new acceptance.
    await fs.writeFile(
      path.join(root, "design/decisions/DDR-003-post-alpha.md"),
      decision("DDR-003", "Post alpha"),
    );
    await fs.writeFile(
      path.join(root, "design/decisions/DDR-001-widgets.md"),
      ACCEPTED_DDR.replace("context_source: test", "amended_by: [DDR-003]\ncontext_source: test"),
    );
    git("add", "-A");
    git("commit", "-m", "ddr-3");

    const content = await collectHandoffContent(root, INPUTS);
    expect(content.previousTag).toBe("alpha");
    expect(content.ddrs.map((d) => d.title)).toEqual(["DDR-003 — Post alpha"]);
  });

  it("hands over the questions still open, and only those (TASK-464)", async () => {
    const root = await makeDesignRepo(sandbox);
    await fs.mkdir(path.join(root, "design/questions"), { recursive: true });
    await fs.writeFile(
      path.join(root, "design/questions/QUESTION-001.md"),
      "---\ntype: Question\nid: QUESTION-001\ntitle: Can tier names change without legal review?\ndate: 2026-07-19\nquestion_status: open\ncontext: DDR-001\n---\n",
    );
    await fs.writeFile(
      path.join(root, "design/questions/QUESTION-002.md"),
      "---\ntype: Question\nid: QUESTION-002\ntitle: Settled already\ndate: 2026-07-20\nquestion_status: resolved\nresolution: DDR-001\n---\n",
    );

    const content = await collectHandoffContent(root, INPUTS);
    expect(content.openQuestions).toEqual([
      {
        id: "QUESTION-001",
        title: "Can tier names change without legal review?",
        date: "2026-07-19",
        context: "DDR-001",
      },
    ]);

    // And it reaches the pack: the docx is a zip whose document.xml is
    // deflated, so it is read out rather than grepped.
    const { files } = await generateHandoffPack(root, INPUTS);
    const xml = zipEntry(await fs.readFile(files[1] as string), "word/document.xml");
    expect(xml).toContain("Open questions");
    expect(xml).toContain("QUESTION-001 · Can tier names change without legal review?");
    expect(xml).toContain("bears on DDR-001");
  });
});

/** One entry of a zip, by way of the central directory, which always carries the sizes. */
function zipEntry(zip: Buffer, name: string): string {
  const eocd = zip.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  if (eocd < 0) throw new Error("not a zip");
  let offset = zip.readUInt32LE(eocd + 16);
  while (zip.readUInt32LE(offset) === 0x02014b50) {
    const method = zip.readUInt16LE(offset + 10);
    const compressedSize = zip.readUInt32LE(offset + 20);
    const nameLength = zip.readUInt16LE(offset + 28);
    const extraLength = zip.readUInt16LE(offset + 30);
    const commentLength = zip.readUInt16LE(offset + 32);
    const localOffset = zip.readUInt32LE(offset + 42);
    const entryName = zip.toString("utf8", offset + 46, offset + 46 + nameLength);
    if (entryName === name) {
      const dataStart =
        localOffset + 30 + zip.readUInt16LE(localOffset + 26) + zip.readUInt16LE(localOffset + 28);
      const data = zip.subarray(dataStart, dataStart + compressedSize);
      return (method === 8 ? inflateRawSync(data) : data).toString("utf8");
    }
    offset += 46 + nameLength + extraLength + commentLength;
  }
  throw new Error(`${name} is not in the zip`);
}

describe("generateHandoffPack", () => {
  it("writes a real PDF and a real docx into handoff/<tag>/", async () => {
    const root = await makeDesignRepo(sandbox);
    const { files } = await generateHandoffPack(root, INPUTS);

    const pdf = await fs.readFile(path.join(root, "handoff/beta/handoff-beta.pdf"));
    const docx = await fs.readFile(path.join(root, "handoff/beta/handoff-beta.docx"));
    expect(files).toHaveLength(2);
    expect(pdf.subarray(0, 5).toString()).toBe("%PDF-");
    expect(docx.subarray(0, 2).toString()).toBe("PK"); // zip container
    expect(pdf.length).toBeGreaterThan(1000);
    expect(docx.length).toBeGreaterThan(1000);
  });
});

describe("freeze handoff step", () => {
  it("generates and commits the handoff pack as part of the ceremony", async () => {
    const root = await makeDesignRepo(sandbox);
    await runFreeze({ tag: "alpha", message: "first", cwd: root });

    const git = (...args: string[]) => execFileSync("git", args, { cwd: root }).toString().trim();
    expect(git("status", "--porcelain")).toBe("");
    expect(git("ls-files", "handoff/alpha")).toContain("handoff/alpha/handoff-alpha.pdf");
    expect(git("ls-files", "handoff/alpha")).toContain("handoff/alpha/handoff-alpha.docx");
  });
});
