// `forge skills install` — put the agent instructions where an agent reads
// them (DDR-079).
//
// Skills ship inside this package rather than through a marketplace so a
// skill's instructions and the CLI commands they call can never be different
// versions. Installing is therefore a copy, not a download.

import { promises as fs } from "node:fs";
import path from "node:path";
import { SKILL_FILES } from "./generated/skills.js";

/**
 * Marks a file this command wrote, so a rerun can tell its own output from
 * something the user authored. The record already uses this discipline for
 * derived files (`<!-- generated by forge index · do not edit -->`); the same
 * rule applied here is what lets an upgrade overwrite safely.
 */
export const SKILL_MARKER = "<!-- installed by forge skills install · do not edit -->";

export type FileOutcome = "written" | "updated" | "kept";

export interface InstallResult {
  files: Array<{ relPath: string; outcome: FileOutcome }>;
  /** paths left alone because something not ours is already there */
  conflicts: string[];
}

/** The skills, as `<name>/SKILL.md` — README and the Codex adapter are not skills. */
export function skillFiles(): Record<string, string> {
  return Object.fromEntries(
    Object.entries(SKILL_FILES).filter(([relPath]) => relPath.endsWith("/SKILL.md")),
  );
}

export function withMarker(body: string): string {
  return `${SKILL_MARKER}\n${body.startsWith("---") ? body : `\n${body}`}`;
}

async function readIfExists(absPath: string): Promise<string | null> {
  try {
    return await fs.readFile(absPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

/**
 * Writes the skills into `.claude/skills/`.
 *
 * A skill directory is the tool's own instructions, not the user's content, so
 * a file this command previously wrote is replaced without asking — that is
 * what keeps skills in step with the CLI they call. A file it did *not* write
 * is never touched: skill names like `triage` and `freeze` are generic enough
 * that a user may already have their own, and silently replacing one would be
 * the worst possible way to find that out.
 */
export async function installSkills(repoRoot: string): Promise<InstallResult> {
  const files: InstallResult["files"] = [];
  const conflicts: string[] = [];

  for (const [relPath, body] of Object.entries(skillFiles())) {
    const target = path.join(".claude", "skills", relPath);
    const abs = path.join(repoRoot, target);
    const existing = await readIfExists(abs);

    if (existing !== null && !existing.includes(SKILL_MARKER)) {
      conflicts.push(target);
      files.push({ relPath: target, outcome: "kept" });
      continue;
    }

    const next = withMarker(body);
    if (existing === next) {
      files.push({ relPath: target, outcome: "kept" });
      continue;
    }
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, next, "utf8");
    files.push({ relPath: target, outcome: existing === null ? "written" : "updated" });
  }

  return { files, conflicts };
}

export interface AgentsResult {
  outcome: FileOutcome;
  relPath: string;
}

/**
 * Writes the Codex adapter as a root `AGENTS.md`.
 *
 * Deliberately more cautious than the skills above: `AGENTS.md` at a repo root
 * is conventionally the *project's* instructions to its agents, and a user is
 * very likely to have written one. It is only created when absent, or updated
 * when this command wrote the existing one — never merged, never clobbered.
 * `forge init` holds the same line, and for the same reason.
 */
export async function installAgentsAdapter(repoRoot: string): Promise<AgentsResult> {
  const body = SKILL_FILES["AGENTS.md"];
  if (!body) throw new Error("this build carries no AGENTS.md adapter");

  const abs = path.join(repoRoot, "AGENTS.md");
  const existing = await readIfExists(abs);
  if (existing !== null && !existing.includes(SKILL_MARKER)) {
    return { outcome: "kept", relPath: "AGENTS.md" };
  }

  const next = withMarker(body);
  if (existing === next) return { outcome: "kept", relPath: "AGENTS.md" };
  await fs.writeFile(abs, next, "utf8");
  return { outcome: existing === null ? "written" : "updated", relPath: "AGENTS.md" };
}
