// Embeds the repo's skills into the CLI as a generated TS constant, so the
// published package carries them (DDR-079) and `forge skills install` needs no
// network and no second distribution channel.
//
// Same shape as embed-overlay.mjs, for the same reason: the bin is a single
// bundled file and cannot read sibling directories at runtime.
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const cliRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Search upward for `skills/` rather than counting directories to it.
 *
 * This package sits at a different depth in each repository that builds it —
 * `prototype/packages/cli` where the record lives, `packages/cli` once
 * extracted — and a hardcoded `../../../skills` is correct in exactly one of
 * them. It was the extraction blocker last time too, in the overlay's version
 * of this script, and a fixed depth would only move which repository breaks.
 */
function findSkillsRoot(from) {
  for (let dir = from; ; dir = path.dirname(dir)) {
    const candidate = path.join(dir, "skills");
    if (existsSync(candidate) && statSync(candidate).isDirectory()) return candidate;
    if (path.dirname(dir) === dir) {
      throw new Error(`no skills/ directory above ${from} — cannot embed skills`);
    }
  }
}

const skillsRoot = findSkillsRoot(cliRoot);

function walk(dir, base = "") {
  const out = {};
  for (const name of readdirSync(dir).sort()) {
    const abs = path.join(dir, name);
    const rel = base ? `${base}/${name}` : name;
    if (statSync(abs).isDirectory()) Object.assign(out, walk(abs, rel));
    else if (name.endsWith(".md")) out[rel] = readFileSync(abs, "utf8");
  }
  return out;
}

const files = walk(skillsRoot);
const outDir = path.join(cliRoot, "src/generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "skills.ts"),
  `// Generated by scripts/embed-skills.mjs — do not edit.\n` +
    `// Source: the repo's skills/ directory, embedded ${JSON.stringify(new Date().toISOString().slice(0, 10))}.\n` +
    `export const SKILL_FILES: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`,
  "utf8",
);
console.log(`embedded ${Object.keys(files).length} skill file(s)`);
